### ISSUE TITLE
Could you provide a 32-Bit (x86) binary?

### ISSUE THREAD

**Issue by Dragodraki** [Beej126/Elevator#1]
For some old Windows OS I'd like to work on 32-Bit OS, but your app "elevator" is written on 64-Bit only.
-> Please, could you compile your project in Visual Studio with x86 architecture and upload it here on github?
I tried it on my pc (VS2017) with your source, but project throws many errors (probably not meant for my set in VS 2017 to handle).

**Comment by Beej126** [comment]
@Dragodraki - [this new build](https://github.com/Beej126/Elevator/releases/tag/1.2) ran locally for me and shows up as 32bitness, hopefully works for you?

**Comment by Dragodraki** [comment]
May work, but according to VirusTotal 
https://www.virustotal.com/gui/file/1313b5177ceee06180b28d9b68aa2e9929b721d3ba0e0af99bad09f10329b07b?nocache=1
this version seems to contain virus.
Your original 64-Bit app hasn't this problem.
Could you compile your app so that not so many Antivirus will flag it as malware on VirusTotal?

**Comment by Beej126** [comment]
[according to this](https://www.reddit.com/r/VisualStudio/comments/qfdy2o/i_noticed_that_x86_vs2019_projects_are_flagged_as/) for 32bit exe's one needs to sign with certificate and then submit that cert to the anti-virus vendors for whitelisting. naturally this project isn't at the scale where i'm motivated to do all that =)

**Comment by Beej126** [comment]
compiled with vs2017 which brought it down to one warning

**Comment by Dragodraki** [comment]
Great! Thank you very much!

**Comment by Dragodraki** [comment]
I assume you can close #1
